language: ruby
cache: bundler
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
notifications:
  email: false
  irc:
    channels:
    - secure: "ph7f8oSBHJCJXZl6/4mgckX60qi+iZ/1T8H4ey/gUk4KKQ1lf3HaVENWLRZk0ULuRCoeagsByFFahqaDbf5roxsZY4lwgZxEcsRUvkYwFQ2ichl36U4QPXgoVoXfnumb7HOlCrqJrB9fnvLOJ3hgFPDMtwG4eYg7AFAZBgechBM="
    template:
    - '%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}'
